---
# https://yamllint.readthedocs.io/en/stable/rules.html
extends: default
rules:
  line-length:
    max: 120
    level: warning
  empty-values:
    forbid-in-block-mappings: true
    forbid-in-flow-mappings: true
    forbid-in-block-sequences: true