# This is a valid YAML file
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: myapp

spec:
  containers:
    - name: mycontainer
      image: nginx:latest
      ports:
        - containerPort: 80
