name: Build and Publish Image to Docker Hub

on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/yaml-guard:latest

    - name: Push image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/yaml-guard:latest
    
    - name: Run yamllint tests on yamls-to-test directory
      continue-on-error: true
      run: |
        docker run --rm \
          -v "$PWD/yamls-to-test":/yamls \
          ${{ secrets.DOCKERHUB_USERNAME }}/yaml-guard:latest \
          yamllint -c /src/.yamllint /yamls
