name: Build and Publish Image to Docker Hub

on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t dogancan4040/yaml-guard:latest
    - name: Push image to Docker Hub
      run: |
        docker push dogancan4040/yaml-guard:latest
