name: Build and Publish Image to Docker Hub

on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/yaml-guard:latest

    - name: Run yamllint tests on yamls-to-test directory
      run: |
        docker run --rm \
          -v "$PWD/yamls-to-test":/yamls \
          ${{ secrets.DOCKERHUB_USERNAME }}/yaml-guard:latest \
          yamllint -c /src/.yamllint /yamls \
          | sed 's/\r$//' | sed 's/ *$//' | sort > actual_output.txt || true
    
    - name: Normalize, sort and compare yamllint outputs
      run: |
        sed 's/\r$//' yamls-to-test/expected_output.txt | sed 's/ *$//' | sort > expected_output_clean.txt
        echo "Comparing actual and expected outputs..."
        diff_output=$(diff -u expected_output_clean.txt actual_output.txt || true)

        if [ -n "$diff_output" ]; then
          echo "$diff_output"
          echo "::error::Output mismatch detected! See diff above."
          exit 1
        else
          echo "Output matches expected!"
        fi
    - name: Push image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/yaml-guard:latest